Repository googleapis/java-datastore, pull requests merged in 2020-07, with the labels that each got.

#190 build: add javax.annotation-api maven-dependency-plugin ignore for java9+ profile activation
  pom.xml
Labels: cla: yes

#185 ci(java): run dependency test on Java 8 and 11
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, context: full

#168 samples: migrate samples from GoogleCloudPlatform/java-docs-samples /datastore
  samples/snippets/src/main/java/com/google/datastore/snippets/TaskList.java
  samples/snippets/src/test/java/com/google/datastore/snippets/ConceptsTest.java
Labels: cla: no

#169 samples: migrate samples from GoogleCloudPlatform/java-docs-samples /datastore/cloud-client
  samples/snippets/src/main/java/com/example/datastore/QuickstartSample.java
  samples/snippets/src/test/java/com/example/datastore/QuickstartSampleIT.java
Labels: cla: no

#153 chore: regenerate CODEOWNERS from templates
  .github/CODEOWNERS
  .repo-metadata.json
  synth.metadata
Labels: automerge, cla: yes

#193 Add cloud-RAD for Java
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: cla: yes, context: full
