Repository googleapis/java-datastore, pull requests merged in 2020-11, with the labels that each got.

#256 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: datastore, cla: yes, context: full

#257 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: datastore, cla: yes, context: full

#258 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: full

#259 deps: update google-cloud-shared-dependencies to 0.15.0
  pom.xml
Labels: api: datastore, automerge, cla: yes

#261 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datastore, automerge, cla: yes

#262 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: datastore, cla: yes, context: full

#268 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: full

#273 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: full, samples

#267 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datastore, cla: yes
