Repository googleapis/java-datastore, pull requests merged in 2020-06, with the labels that each got.

#144 fix: update retry logic for operations that can be associated with a transaction
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreImpl.java
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/TransactionOperationExceptionHandler.java
  google-cloud-datastore/src/test/java/com/google/cloud/datastore/ITDatastoreTest.java
Labels: cla: yes

#145 fix: fix version number in changelog to correctly reflect what was released to maven central
  CHANGELOG.md
Labels: cla: yes

#137 feat: add support to customize gcloud command of LocalDatastoreHelper
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/testing/LocalDatastoreHelper.java
  google-cloud-datastore/src/test/java/com/google/cloud/datastore/testing/ITLocalDatastoreHelperTest.java
Labels: cla: yes

#152 DO NOT MERGE: add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: cla: yes, context: full, do not merge

#130 feat: add opencensus tracing/stats support
  google-cloud-datastore/pom.xml
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreImpl.java
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/TraceUtil.java
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/spi/v1/HttpDatastoreRpc.java
  pom.xml
Labels: cla: yes

#155 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .kokoro/build.sh
  renovate.json
  synth.metadata
Labels: cla: yes, context: full

#162 chore: set Ruby namespace in proto options
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/DatastoreProto.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/EntityProto.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/QueryProto.java
  proto-google-cloud-datastore-v1/src/main/proto/google/datastore/v1/datastore.proto
  proto-google-cloud-datastore-v1/src/main/proto/google/datastore/v1/entity.proto
  proto-google-cloud-datastore-v1/src/main/proto/google/datastore/v1/query.proto
  synth.metadata
Labels: cla: yes, context: full

#166 ci: update CI config to use secret manager integration for credentials
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, context: full

#174 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  pom.xml
  proto-google-cloud-datastore-v1/pom.xml
Labels: cla: yes

#179 chore: update client_documentation link
  .repo-metadata.json
Labels: cla: yes

#184 deps: remove direct declaration of google-auth-library-oauth2-http
  pom.xml
Labels: cla: yes
