Repository googleapis/java-datastore, pull requests merged in 2020-12, with the labels that each got.

#281 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: full

#276 fix(docs): broken links
  README.md
Labels: api: datastore, cla: yes

#285 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datastore, automerge, cla: yes

#292 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datastore, automerge, cla: yes

#293 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: full

#296 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: datastore, cla: yes, context: full
