Repository googleapis/java-datastore, pull requests merged in 2020-10, with the labels that each got.

#225 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: api: datastore, cla: yes, context: full

#226 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#231 ci(java): suggest formatting fixes
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: full

#233 ci(java): restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#235 build(java): auto-approve README regeneration
  .github/workflows/approve-readme.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#234 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datastore, cla: yes

#237 build(java): enable snippet-bot
  .github/snippet-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#236 docs: update google cloud libraries-bom
  README.md
Labels: api: datastore, automerge, cla: yes

#239 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#238 chore: clean up and update renovate.json
  renovate.json
  synth.metadata
Labels: api: datastore, cla: yes, context: full

#247 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#248 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#249 chore: regenerate common templates
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: full

#252 chore(ci): fix typo in restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#253 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#255 chore(java): enable generated-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full
