Repository googleapis/java-datastore, pull requests merged in 2020-05, with the labels that each got.

#121 chore: regenerate proto files
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/Value.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/ValueOrBuilder.java
  proto-google-cloud-datastore-v1/src/main/proto/google/datastore/v1/entity.proto
  synth.metadata
Labels: cla: yes, context: full

#122 feat: Create CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes

#123 ci: enable GitHub actions
  .github/workflows/ci.yaml
  .kokoro/build.bat
  synth.metadata
Labels: automerge, cla: yes, context: full

#124 docs: update CONTRIBUTING.md to include code formatting (#534)
  CONTRIBUTING.md
  synth.metadata
Labels: cla: yes, context: full

#125 chore: remove unused maven project properties
  pom.xml
Labels: cla: yes

#126 docs: fix java doc link of LocalDatastoreHelper#stop
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/testing/LocalDatastoreHelper.java
Labels: cla: yes

#135 feat: implement google-cloud-shared-dependencies BOM
  pom.xml
Labels: cla: yes

#139 deps: bump shared-deps version and add back certain test deps
  pom.xml
Labels: automerge, cla: yes

#141 bazel: update protobuf, rules_go, gazelle, and gapic-generator-go versions
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/AllocateIdsRequest.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/AllocateIdsResponse.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/ArrayValue.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/BeginTransactionRequest.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/BeginTransactionResponse.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/CommitRequest.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/CommitResponse.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/CompositeFilter.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/Entity.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/EntityResult.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/Filter.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/GqlQuery.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/GqlQueryParameter.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/Key.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/KindExpression.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/LookupRequest.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/LookupResponse.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/Mutation.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/MutationResult.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/PartitionId.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/Projection.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/PropertyFilter.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/PropertyOrder.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/PropertyReference.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/Query.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/QueryResultBatch.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/ReadOptions.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/ReserveIdsRequest.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/RollbackRequest.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/RunQueryRequest.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/RunQueryResponse.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/TransactionOptions.java
  proto-google-cloud-datastore-v1/src/main/java/com/google/datastore/v1/Value.java
  synth.metadata
Labels: cla: yes, context: full
