Repository googleapis/java-datastore, pull requests merged in 2020-09, with the labels that each got.

#213 chore(build): update synth config to generate README.md
  .readme-partials.yaml
  .repo-metadata.json
  README.md
  synth.py
Labels: cla: yes

#214 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: datastore, cla: yes, context: full

#216 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: api: datastore, cla: yes, context: full

#218 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: datastore, cla: yes, context: full

#217 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: datastore, cla: yes

#219 chore(ci): skip autorelease workflow on non-release PRs and release PRs without content changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: datastore, cla: yes, context: full

#220 docs: update libraries-bom
  README.md
Labels: cla: yes

#223 chore(java): use separate autosynth job for README
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#224 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
