Repository googleapis/java-datastore, pull requests merged in 2020-08, with the labels that each got.

#197 cleanup: removes unused kokoro config files
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: cla: yes, context: full

#198 build: update dependencies check to only check for runtime and compile scopes
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, context: full

#200 docs: libraries-bom 8.1.0
  README.md
Labels: automerge, cla: yes

#203 chore(java_templates): add lint/static analysis presubmit checks for samples
  .github/workflows/samples.yaml
  synth.metadata
Labels: cla: yes, context: full

#208 build: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: datastore, cla: yes, context: full

#210 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: cla: yes, context: full

#207 fix: QueryResults return startCursor if specified
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/QueryResultsImpl.java
  google-cloud-datastore/src/test/java/com/google/cloud/datastore/ITDatastoreTest.java
  google-cloud-datastore/src/test/java/com/google/cloud/datastore/it/ITDatastoreTest.java
Labels: api: datastore, cla: yes

#211 docs: update libraries-bom
  README.md
Labels: api: datastore, cla: yes
