Repository googleapis/java-datastore, pull requests merged in 2021-09, with the labels that each got.

#529 chore(java): install maven 3.8.1 at runtime
  .github/workflows/ci.yaml
  synth.metadata
Labels: kokoro:force-run, cla: yes, automerge, api: datastore, context: full

#531 chore(java): update windows build
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: datastore, context: full

#532 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, automerge, api: datastore

#533 chore: remove readme autosynth config
  .kokoro/continuous/readme.cfg
Labels: cla: yes, api: datastore

#535 chore: synthtool template updates
  .github/readme/synth.py
  .github/trusted-contribution.yml
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, api: datastore, context: partial

#547 chore(java): remove dependencyDashboardLabel config from renovate.json
  renovate.json
  synth.metadata
Labels: cla: yes, api: datastore, context: full

#506 feat: Change checksum algorithm to CRC32C. And localize checksum handling t…
  datastore-v1-proto-client/src/main/java/com/google/datastore/v1/client/ChecksumEnforcingInputStream.java
  datastore-v1-proto-client/src/main/java/com/google/datastore/v1/client/EndToEndChecksumHandler.java
  datastore-v1-proto-client/src/main/java/com/google/datastore/v1/client/RemoteRpc.java
  datastore-v1-proto-client/src/test/java/com/google/datastore/v1/client/ChecksumEnforcingInputStreamTest.java
  datastore-v1-proto-client/src/test/java/com/google/datastore/v1/client/RemoteRpcTest.java
Labels: cla: yes, api: datastore

#548 chore: re-generated to pick up changes from synthtool
  .github/blunderbuss.yml
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, api: datastore, context: full

#550 chore: change branch master to main in github configurations
  .github/sync-repo-settings.yaml
  README.md
Labels: cla: yes, automerge, api: datastore
