Repository googleapis/java-datastore, pull requests merged in 2021-08, with the labels that each got.

#483 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: full

#490 feat!: upgrade shared dependencies to 2.0.0
  datastore-v1-proto-client/pom.xml
  pom.xml
Labels: cla: yes, automerge, api: datastore

#495 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, automerge, api: datastore

#501 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: cla: yes, api: datastore, context: full

#502 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, automerge, api: datastore

#504 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, automerge, api: datastore

#513 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, automerge, api: datastore

#517 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, automerge, api: datastore

#515 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, automerge, api: datastore

#520 ci: removing linkage-monitor from the required checks
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, automerge, api: datastore, context: full

#523 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, automerge, api: datastore

#525 build(java): update renovate config to mark conformance tests as a test commit type
  renovate.json
  synth.metadata
Labels: cla: yes, automerge, api: datastore, context: full
