Repository googleapis/java-datastore, pull requests merged in 2021-05, with the labels that each got.

#412 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: none

#413 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: full

#416 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datastore, automerge, cla: yes

#421 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datastore, automerge, cla: yes

#422 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datastore, automerge, cla: yes

#423 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: full

#426 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datastore, automerge, cla: yes

#428 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datastore, automerge, cla: yes

#429 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: full

#427 feat: migrate google-cloud-datastore/java into java-datastore
  datastore-v1-proto-client/pom.xml
  datastore-v1-proto-client/src/main/java/com/google/datastore/v1/client/ChecksumEnforcingInputStream.java
  datastore-v1-proto-client/src/main/java/com/google/datastore/v1/client/Datastore.java
  datastore-v1-proto-client/src/main/java/com/google/datastore/v1/client/DatastoreEmulator.java
  datastore-v1-proto-client/src/main/java/com/google/datastore/v1/client/DatastoreEmulatorException.java
  datastore-v1-proto-client/src/main/java/com/google/datastore/v1/client/DatastoreEmulatorFactory.java
  datastore-v1-proto-client/src/main/java/com/google/datastore/v1/client/DatastoreEmulatorOptions.java
  datastore-v1-proto-client/src/main/java/com/google/datastore/v1/client/DatastoreException.java
  datastore-v1-proto-client/src/main/java/com/google/datastore/v1/client/DatastoreFactory.java
  datastore-v1-proto-client/src/main/java/com/google/datastore/v1/client/DatastoreHelper.java
  datastore-v1-proto-client/src/main/java/com/google/datastore/v1/client/DatastoreOptions.java
  datastore-v1-proto-client/src/main/java/com/google/datastore/v1/client/EndToEndChecksumHandler.java
  datastore-v1-proto-client/src/main/java/com/google/datastore/v1/client/QuerySplitter.java
  datastore-v1-proto-client/src/main/java/com/google/datastore/v1/client/QuerySplitterImpl.java
  datastore-v1-proto-client/src/main/java/com/google/datastore/v1/client/RemoteRpc.java
  datastore-v1-proto-client/src/test/java/com/google/datastore/v1/client/ChecksumEnforcingInputStreamTest.java
  datastore-v1-proto-client/src/test/java/com/google/datastore/v1/client/DatastoreEmulatorTest.java
  datastore-v1-proto-client/src/test/java/com/google/datastore/v1/client/DatastoreFactoryTest.java
  datastore-v1-proto-client/src/test/java/com/google/datastore/v1/client/DatastoreHelperTest.java
  datastore-v1-proto-client/src/test/java/com/google/datastore/v1/client/DatastoreTest.java
  datastore-v1-proto-client/src/test/java/com/google/datastore/v1/client/EndToEndChecksumHandlerTest.java
  datastore-v1-proto-client/src/test/java/com/google/datastore/v1/client/RemoteRpcTest.java
  pom.xml
  versions.txt
Labels: api: datastore, cla: yes

#433 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: full

#439 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datastore, automerge, cla: yes

#438 feat: configure initial sp version
  .github/workflows/ci.yaml
Labels: api: datastore, cla: yes

#437 build: configure branch 1.106.5-sp as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: datastore, automerge, cla: yes

#441 deps: align dependencies to 1.106.0 release
  google-cloud-datastore-bom/pom.xml
  pom.xml
Labels: api: datastore, cla: yes

#449 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datastore, automerge, cla: yes

#444 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: full
