Repository googleapis/java-datastore, pull requests merged in 2021-06, with the labels that each got.

#454 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datastore, automerge, cla: yes

#455 chore: create flakybot.yaml
  .github/flakybot.yaml
Labels: api: datastore, cla: yes

#456 fix: Update dependencies.sh to not break on mac
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: full

#459 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datastore, automerge, cla: yes

#460 chore: minimize noise from build scripts
  .kokoro/coerce_logs.sh
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: full

#461 fix: Add `shopt -s nullglob` to dependencies script
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: full

#464 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datastore, automerge, cla: yes

#466 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datastore, automerge, cla: yes
