Repository googleapis/java-datastore, pull requests merged in 2022-11, with the labels that each got.

#809 samples: Add example snippet for snapshot reads
  samples/snippets/src/test/java/com/google/datastore/snippets/ConceptsTest.java
Labels: api: datastore, samples, size: s

#918 ci: configure the protected branch
  .github/workflows/ci.yaml
Labels: api: datastore, size: m

#917 feat: next release from main branch is 2.13.0
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: datastore, size: s

#927 chore: add new branch to sync-repo-settings
  .github/sync-repo-settings.yaml
Labels: automerge, api: datastore, size: s
