Repository googleapis/java-datastore, pull requests merged in 2022-02, with the labels that each got.

#629 deps: update shared dependencies to 2.7.0 and remove google-oauth-client from dependency management
  pom.xml
Labels: api: datastore

#626 deps(java): update actions/github-script action to v5
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: datastore, context: full

#635 chore: add kokoro config to run nightly integration test on java11.0.14
  .kokoro/nightly/java11-integration.cfg
  synth.metadata
Labels: api: datastore, context: full

#632 fix: Use ImmutableMap.Builder.buildOrThrow() instead of build().
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/GqlQuery.java
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/ReadOption.java
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/ValueType.java
  google-cloud-datastore/src/test/java/com/google/cloud/datastore/ValueTest.java
Labels: api: datastore

#640 docs(sample): Add sample for native image support in Datastore
  samples/native-image-sample/README.md
  samples/native-image-sample/pom.xml
  samples/native-image-sample/src/main/java/com/example/datastore/NativeImageDatastoreSample.java
  samples/native-image-sample/src/test/java/com/example/datastore/ITNativeImageDatastoreSample.java
  samples/pom.xml
Labels: api: datastore, samples
