Repository googleapis/java-datastore, pull requests merged in 2023-07, with the labels that each got.

#1144 chore: setup 2.15.x lts branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: datastore, size: s

#1145 ci: configure the protected branch
  .github/workflows/ci.yaml
Labels: api: datastore, size: m

#1146 deps: shared-dependencies 3.13.0
  pom.xml
Labels: api: datastore, size: xs

#1152 chore: remove BetaApi annotation from OR query API (#1118)
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/StructuredQuery.java
Labels: automerge, api: datastore, owlbot:ignore, size: xs

#1153 docs: fix javadoc errors (#1126)
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/AggregationQuery.java
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/AggregationResults.java
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/Datastore.java
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/GqlQuery.java
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/Query.java
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/StructuredQuery.java
Labels: automerge, api: datastore, owlbot:ignore, size: s
