Repository googleapis/java-datastore, pull requests merged in 2024-07, with the labels that each got.

#1506 chore: correct hermetic library generation script path
  .github/workflows/hermetic_library_generation.yaml
  README.md
Labels: api: datastore, size: xs

#1505 test: Additional Transaction Testing and cleanup OpenCensus usage
  google-cloud-datastore/clirr-ignored-differences.xml
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreImpl.java
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/RetryAndTraceDatastoreRpcDecorator.java
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/TraceUtil.java
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/spi/v1/HttpDatastoreRpc.java
  google-cloud-datastore/src/test/java/com/google/cloud/datastore/it/ITE2ETracingTest.java
Labels: automerge, api: datastore, size: m

#1510 chore: skip hermetic generation on fork PRs
  .github/workflows/hermetic_library_generation.yaml
Labels: api: datastore, size: xs

#1512 chore: make the owlbot postprocessor check non-required
  .github/sync-repo-settings.yaml
Labels: api: datastore, size: xs

#1511 chore: disable the Owl Bot post-processor
  .github/.OwlBot.lock.yaml
Labels: api: datastore, size: s

#1514 test: Adding ITTracingTest to verify events and span attributes (whic…
  google-cloud-datastore/pom.xml
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreImpl.java
  google-cloud-datastore/src/test/java/com/google/cloud/datastore/it/ITE2ETracingTest.java
  google-cloud-datastore/src/test/java/com/google/cloud/datastore/it/ITTracingTest.java
Labels: api: datastore, size: l

#1518 test: Additional Transaction tests and AggregationQuery test
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreImpl.java
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/telemetry/DisabledTraceUtil.java
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/telemetry/EnabledTraceUtil.java
  google-cloud-datastore/src/main/java/com/google/cloud/datastore/telemetry/TraceUtil.java
  google-cloud-datastore/src/test/java/com/google/cloud/datastore/it/ITTracingTest.java
Labels: api: datastore, size: l

#1535 chore: setup 2.19.x lts branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: datastore, size: s
